### ISSUE TITLE
Tracking issue for semver spec translation

### ISSUE THREAD

**Issue by JanLikar** [JanLikar/semver.org#1]
- [x] Povzetek
- [ ] Uvod
- [ ] Specifikacija semantičnih verzij (SemVer)
- [ ] Zakaj uporabljati semantične verzije?
- [x] Kako ravnam z revizijami v 0.y.z začetni fazi razvoja?
- [x] Kako vem, kdaj izdati 1.0.0?
- [x] Ali to ne odvrača hitrega razvoja in hitrih interacij?
- [x]  Če tudi najmanjša nazaj nezdružljiva sprememba javnega API-ja zahteva povečanje glavne verzije, 
- [x]  Dokumentiranje celotnega javnega API-ja je preveč dela!
- [x] Kaj narediti, če ponesreči izdam nazaj nezdružljivo spremembo kot manjšo verzijo
- [ ]  Kaj naj naredim, če posodobim svoje lastne odvisnosti brez spremembe javnega API-ja?
- [ ] Kaj če nehote spremenim javni API na način, ki ni skladen s spremembo številke verzije (t.j. koda 
- [ ]  Kako ravnam z opuščenimi funkcionalnostmi?
- [x]  Ali ima semver omejitev velikosti na nizu verzije?
- [x] O projektu
